name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'advanced/submissions/team-members/brian-malone/fast-api-car-price/**'
      - '.github/workflows/ci.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'advanced/submissions/team-members/brian-malone/fast-api-car-price/**'
      - '.github/workflows/ci.yml'

  workflow_dispatch:

env:
  DOCKER_IMAGE: bjmalone724/car-price-api

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: advanced/submissions/team-members/brian-malone/fast-api-car-price

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest httpx
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest tests/ --verbose --tb=short

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    defaults:
      run:
        working-directory: advanced/submissions/team-members/brian-malone/fast-api-car-price

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=sha,prefix=main-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./advanced/submissions/team-members/brian-malone/fast-api-car-price
          file: ./advanced/submissions/team-members/brian-malone/fast-api-car-price/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:latest
          cache-to: type=inline

      - name: Output image tags
        run: |
          echo "🐳 Docker image pushed:"
          echo "${{ steps.meta.outputs.tags }}"
